FROM centos:7.7.1908
ARG _ARCH=x86_64
ARG _UID=2244
ARG _GID=101
ARG _LOGIN=jenkins
ARG _HOME=/var/home/$_LOGIN
USER root

RUN yum install -y \
    atk \
    autoconf \
    automake \
    cairo \
    ethtool \
    gcc-gfortran \
    gcc-c++ \
    git \
    gtk2 \
    libmnl \
    libnl3 \
    libtool \
    lsof \
    make \
    numactl-libs \
    pciutils \
    perl \
    rpm-build \
    sudo \
    tcl \
    tcsh \
    tk \
    default-jdk \
    environment-modules \
    rdma-core-devel \
    libusbx fuse-libs \
	libibverbs-dev \
	libfile-fcntllock-perl \
	chrpath flex gfortran graphviz dpatch libgfortran3 tcl bison tk swig \
    wget

RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

RUN mkdir -p $_HOME
RUN groupadd -f -g "$_GID" "$_LOGIN"
RUN useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "$_LOGIN"
RUN chown $_LOGIN $_HOME

ENV MODULEPATH /hpc/local/etc/modulefiles
SHELL ["/bin/bash"] 

USER "${_LOGIN}"
ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]
