#!/usr/bin/groovy


node("master") {

    stage("Prepare load lib") {
        checkout scm
    }

    // load pipeline functions
    sh("ls -al ; ls -al src")
    def matrix = load('src/com/mellanox/cicd/Matrix.groovy')
    matrix.main()
}
