#!/usr/bin/groovy


node("master") {

    stage("Prepare load lib") {
        checkout scm
    }

    stage ("Load Lib") {
        // load pipeline functions
        def libname = pwd() + '/src/com/mellanox/cicd/Matrix.groovy'
        def mylib = load(libname)
        if (mylib) {
            mylib.main()
        } else {
            println("[Error] Cannot load " + libname)
        }
    }
}
